#!/bin/bash
# ============================================================================
# lockfiles_check.sh - Verify pip-tools lockfiles are in sync
# ============================================================================
# Usage: ./scripts/lockfiles_check.sh
#
# Exits 0 if lockfiles are in sync, non-zero otherwise.
# Designed for local development and CI use.
# ============================================================================

set -e

echo "=== Lockfile Sync Check ==="
echo ""

# Ensure pip-tools is available
if ! command -v pip-compile &> /dev/null; then
    echo "Installing pip-tools..."
    pip install pip-tools
fi

# Check requirements.txt has pip-compile header
echo "Checking for pip-compile header..."
if ! head -10 requirements.txt | grep -q "autogenerated by pip-compile"; then
    echo "ERROR: requirements.txt is missing pip-compile header!"
    echo "This file MUST be generated by pip-compile, not edited directly."
    exit 1
fi
echo "✓ Header check passed"
echo ""

# Generate fresh lockfile
echo "Generating fresh lockfile..."
pip-compile --resolver=backtracking --generate-hashes --strip-extras \
    -o /tmp/requirements_check.txt requirements.in 2>/dev/null

# Compare
echo "Comparing lockfiles..."
if ! diff -u requirements.txt /tmp/requirements_check.txt; then
    echo ""
    echo "ERROR: requirements.txt is OUT OF SYNC with requirements.in!"
    echo ""
    echo "To fix, run:"
    echo "  pip-compile --resolver=backtracking --generate-hashes --strip-extras requirements.in"
    exit 1
fi

echo ""
echo "✓ Lockfiles are in sync!"
exit 0
